spring:
  application:
    name: api-library
  flyway:
    enabled: false
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cache:
    type: redis

security:
  jwt:
    expiration-time: ${JWT_EXPIRATION:86400000}
    secret-key: ${JWT_SECRET:YourFallbackSuperSecretKeyForLocalDevelopmentOnly}
