spring:
  application:
    cors:
      allowed-origins: "http://localhost:4200,http://localhost:3000"

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:library_db}
    username: ${DB_USER:user_admin}
    password: ${DB_PASSWORD:librarypassword}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
