spring:
  application:
    name: api-library
  flyway:
    enabled: false
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cache:
    type: redis

security:
  jwt:
    expiration-time: ${SECURITY_JWT_EXPIRATION_TIME:86400000}