services:
  db:
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: librarypassword
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  # This is the base config for the dev environment
  api:
    image: ${DOCKER_USERNAME}/api-library:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SECURITY_JWT_SECRET_KEY: YourFallbackSuperSecretKeyForLocalDevelopmentOnly
      SECURITY_JWT_EXPIRATION_TIME: 86400000
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/library_db
      SPRING_DATASOURCE_USERNAME: user_admin
      SPRING_DATASOURCE_PASSWORD: librarypassword
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - db
      - redis
